<script setup lang="ts">
import { PhArrowRight, PhCalendarCheck, PhCamera, PhClock, PhCurrencyCircleDollar, PhDeviceMobile, PhWarning } from '@phosphor-icons/vue'
import { computed, onMounted, ref } from 'vue'
import AdminLayout from '@/layouts/AdminLayout.vue'
import StatePanel from '@/components/StatePanel.vue'
import { getAdminOverview, type AdminPreviewMode } from '@/services/admin'
import type { AdminOverviewSnapshot } from '@/services/analytics'
import { useDemoStore } from '@/stores/demo'
import { formatIdr } from '@/utils/currency'
import { formatWita } from '@/utils/datetime'

const demo = useDemoStore(); const overview = ref<AdminOverviewSnapshot>(); const loading = ref(true); const failed = ref(false)
const maxTrend = computed(() => Math.max(1, ...(overview.value?.trend.map(point => point.count) ?? [1])))
function mode(): AdminPreviewMode { const active = demo.activeScenario; return active?.id === 'admin-overview-empty' ? 'empty' : active?.mode === 'loading' ? 'loading' : active?.mode === 'recoverable_error' ? 'error' : 'normal' }
async function load() { loading.value = true; failed.value = false; try { overview.value = await getAdminOverview(mode()) } catch { failed.value = true } finally { loading.value = false } }
onMounted(() => { demo.hydrate(); load() })
</script>

<template><AdminLayout><div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-10"><div><p class="text-sm font-extrabold text-muted">Operasional prototype</p><h1 class="mt-1 text-3xl font-black tracking-tight sm:text-4xl">Ringkasan Admin</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-muted">Semua angka dihitung dari booking demo yang sama dengan riwayat pelanggan. Bukan data real-time.</p></div>
  <StatePanel v-if="loading" class="mt-8" state="loading" title="Menghitung ringkasan" message="Mengolah booking dalam waktu WITA." />
  <StatePanel v-else-if="failed" class="mt-8" state="error" title="Ringkasan belum dapat dimuat" message="Kesalahan demo dapat dipulihkan tanpa mengubah booking." @retry="load" />
  <StatePanel v-else-if="overview && !overview.trend.some(point => point.count) && !overview.attention.length && overview.estimatedRevenue === 0" class="mt-8" state="empty" title="Belum ada data operasional" message="Aktifkan skenario berisi data untuk melihat metrik dan perhatian staf." />
  <template v-else-if="overview"><section class="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><RouterLink v-for="metric in [{ label: 'Booking dibuat hari ini', value: overview.bookingsToday, filter: 'created_today', icon: PhCalendarCheck }, { label: 'Rental aktif sekarang', value: overview.activeRentals, filter: 'active', icon: PhClock }, { label: 'Pengambilan 7 hari', value: overview.upcomingPickups, filter: 'upcoming_pickup', icon: PhCalendarCheck }]" :key="metric.label" :to="`/admin/bookings?filter=${metric.filter}`" class="group rounded-2xl border border-sand bg-white p-5"><component :is="metric.icon" :size="22" /><p class="mt-5 text-3xl font-black tabular-nums">{{ metric.value }}</p><p class="mt-1 text-sm font-bold text-muted">{{ metric.label }}</p><span class="mt-4 flex items-center gap-2 text-xs font-black">Lihat booking <PhArrowRight class="transition-transform group-hover:translate-x-1" /></span></RouterLink><RouterLink to="/admin/bookings" class="group rounded-2xl border border-sand bg-brand-yellow p-5"><PhCurrencyCircleDollar :size="22" /><p class="mt-5 text-2xl font-black tabular-nums">{{ formatIdr(overview.estimatedRevenue) }}</p><p class="mt-1 text-sm font-bold">Estimasi rental bulan ini</p><span class="mt-4 flex items-center gap-2 text-xs font-black">Lihat booking <PhArrowRight /></span></RouterLink></section>
  <p class="mt-3 text-xs leading-5 text-muted">Estimasi rental berdasarkan subtotal booking, bukan kas diterima, pendapatan akuntansi, pajak, biaya, refund, atau profit.</p>
  <div class="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(18rem,.65fr)]"><section class="rounded-2xl border border-sand bg-white p-5 sm:p-6"><div class="flex items-end justify-between gap-4"><div><h2 class="text-xl font-black">Booking dibuat dalam 30 hari</h2><p class="mt-1 text-xs text-muted">Dikelompokkan per tanggal kalender WITA.</p></div><strong>{{ overview.trend.reduce((sum, point) => sum + point.count, 0) }} booking</strong></div><div class="mt-6 grid h-36 grid-cols-[repeat(30,minmax(0,1fr))] items-end gap-1 border-b border-sand" role="img" aria-label="Grafik jumlah booking 30 hari"><div v-for="point in overview.trend" :key="point.date" class="bg-ink transition-colors hover:bg-brand-yellow" :style="{ height: point.count ? `${Math.max(4, point.count / maxTrend * 100)}%` : '0%' }" :title="`${point.date}: ${point.count} booking`" /></div><ul class="sr-only"><li v-for="point in overview.trend" :key="`text-${point.date}`">{{ point.date }}: {{ point.count }} booking</li></ul><p class="mt-3 text-xs text-muted">{{ overview.trend[0]?.date }} hingga {{ overview.trend.at(-1)?.date }} · Nilai tertinggi {{ maxTrend }} booking per hari.</p></section>
  <section class="rounded-2xl border border-sand bg-white p-5 sm:p-6"><h2 class="text-xl font-black">Distribusi kategori</h2><p class="mt-1 text-xs text-muted">Booking bulan berjalan yang masuk estimasi rental.</p><div class="mt-6 flex h-4 overflow-hidden rounded-full bg-surface" aria-hidden="true"><div class="bg-ink" :style="{ width: `${overview.distribution.camera / Math.max(1, overview.distribution.camera + overview.distribution.iphone) * 100}%` }" /><div class="bg-brand-yellow" :style="{ width: `${overview.distribution.iphone / Math.max(1, overview.distribution.camera + overview.distribution.iphone) * 100}%` }" /></div><div class="mt-5 grid gap-3"><RouterLink to="/admin/bookings?filter=camera" class="flex min-h-12 items-center justify-between rounded-xl bg-surface px-4"><span class="flex items-center gap-2 font-bold"><PhCamera /> Kamera</span><strong>{{ overview.distribution.camera }}</strong></RouterLink><RouterLink to="/admin/bookings?filter=iphone" class="flex min-h-12 items-center justify-between rounded-xl bg-surface px-4"><span class="flex items-center gap-2 font-bold"><PhDeviceMobile /> iPhone</span><strong>{{ overview.distribution.iphone }}</strong></RouterLink></div></section></div>
  <section class="mt-8"><div class="flex items-center gap-3"><PhWarning :size="23" /><div><h2 class="text-xl font-black">Perlu perhatian</h2><p class="text-xs text-muted">Alasan digabung agar satu booking tidak tampil berulang.</p></div></div><p v-if="!overview.attention.length" class="mt-4 rounded-xl border border-sand bg-white p-5 text-sm text-muted">Tidak ada booking yang memerlukan perhatian pada waktu skenario ini.</p><div v-else class="mt-4 grid gap-3"><RouterLink v-for="item in overview.attention" :key="item.booking.id" :to="`/admin/bookings/${item.booking.id}`" class="group grid gap-3 rounded-2xl border border-sand bg-white p-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><strong>{{ item.booking.reference }}</strong><p class="mt-1 text-sm font-bold">{{ item.booking.customerSnapshot.name }} · {{ item.booking.lines[0]?.nameSnapshot }}</p><div class="mt-3 flex flex-wrap gap-2"><span v-for="reason in item.reasons" :key="reason" class="status-badge status-limited">{{ reason }}</span></div></div><div class="text-sm text-muted sm:text-right"><p>{{ formatWita(item.booking.period.pickupAt) }}</p><span class="mt-2 inline-flex items-center gap-2 font-black text-ink">Buka detail <PhArrowRight /></span></div></RouterLink></div></section></template></div></AdminLayout></template>
