<script setup lang="ts">
import { PhCalendarBlank, PhCheckCircle, PhIdentificationCard, PhMapPin } from '@phosphor-icons/vue'
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import CustomerLayout from '@/layouts/CustomerLayout.vue'
import StatePanel from '@/components/StatePanel.vue'
import type { Booking } from '@/domain/models'
import { getBooking } from '@/services/booking'
import { useDemoStore } from '@/stores/demo'
import { formatIdr } from '@/utils/currency'
import { formatWita } from '@/utils/datetime'

const route = useRoute(); const demo = useDemoStore(); const booking = ref<Booking>()
const paid = computed(() => booking.value?.paymentStatus === 'deposit_paid')
onMounted(() => { demo.hydrate(); booking.value = getBooking(String(route.params.bookingId)) })
</script>
<template><CustomerLayout><div class="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:py-16"><StatePanel v-if="!booking" state="not-found" title="Konfirmasi tidak ditemukan" message="Periksa riwayat booking demo untuk melihat data yang tersimpan." /><template v-else><div class="text-center"><span class="mx-auto grid size-14 place-items-center rounded-full" :class="paid ? 'bg-success text-white' : 'bg-brand-yellow'"><PhCheckCircle :size="30" weight="fill" /></span><p class="mt-5 text-sm font-extrabold text-muted">Langkah 3 dari 3</p><h1 class="mt-2 text-3xl font-black">{{ paid ? 'Booking demo dikonfirmasi' : 'Pembayaran demo dikirim' }}</h1><p class="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted">{{ paid ? 'DP simulasi tercatat dan booking berstatus confirmed.' : 'Booking masih menunggu verifikasi simulasi dan belum dikonfirmasi.' }}</p></div><section class="mt-8 rounded-2xl border border-sand bg-white p-6 sm:p-8"><div class="flex flex-wrap justify-between gap-4 border-b border-sand pb-5"><div><p class="text-xs font-bold text-muted">Referensi</p><p class="mt-1 text-xl font-black">{{ booking.reference }}</p></div><div class="flex gap-2"><span class="status-badge status-limited">{{ booking.status }}</span><span class="status-badge" :class="paid ? 'status-available' : 'status-limited'">{{ booking.paymentStatus }}</span></div></div><div class="mt-6 grid gap-6 sm:grid-cols-2"><div><h2 class="font-black">Ringkasan</h2><ul class="mt-3 grid gap-2 text-sm"><li v-for="line in booking.lines" :key="line.id" class="flex justify-between gap-3"><span>{{ line.quantity }}× {{ line.nameSnapshot }}</span><span>{{ formatIdr(line.unitPriceSnapshot) }}</span></li></ul><p class="mt-4 flex justify-between border-t border-sand pt-3"><span>Total</span><strong>{{ formatIdr(booking.pricing.rentalSubtotal) }}</strong></p></div><div><h2 class="font-black">Jadwal</h2><p class="mt-3 flex gap-2 text-sm"><PhCalendarBlank class="shrink-0" />{{ formatWita(booking.period.pickupAt) }}</p><p class="mt-2 pl-6 text-sm">hingga {{ formatWita(booking.period.returnAt) }}</p></div></div><div class="mt-7 grid gap-3 sm:grid-cols-2"><div class="flex gap-3 rounded-xl bg-surface p-4"><PhMapPin class="shrink-0" /><p class="text-sm leading-6">{{ demo.state?.locationAndPolicyCopy.pickupLocation }}</p></div><div class="flex gap-3 rounded-xl bg-surface p-4"><PhIdentificationCard class="shrink-0" /><p class="text-sm leading-6">Bawa dokumen jaminan asli. Jenis yang diterima akan dikonfirmasi.</p></div></div><div class="mt-7 flex flex-wrap justify-center gap-3"><RouterLink class="button-primary inline-flex" to="/my-bookings">Lihat Riwayat</RouterLink><RouterLink class="button-outline inline-flex" :to="{ name: 'customer-booking-detail', params: { bookingId: booking.id } }">Detail Booking</RouterLink></div><p class="mt-5 text-center text-xs text-muted">Tombol kontak nyata tidak disediakan pada prototype ini.</p></section></template></div></CustomerLayout></template>
